# language: minimal
# services: docker
# env:
#   - DOCKER_COMPOSE_VERSION=1.23.2
# before_install:
#   - docker -v && docker-compose -v
#   - sudo rm /usr/local/bin/docker-compose
#   - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
#   - chmod +x docker-compose
#   - sudo mv docker-compose /usr/local/bin
#   - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
#   - chmod +x ./kubectl
#   - sudo mv ./kubectl /usr/local/bin/kubectl

# install:
#   - docker-compose -f docker-compose-build.yml build --parallel
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#   - docker push sidahmedfaisal/udagram-reverseproxy
language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing to install"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy sidahmedfaisal/udagram-reverseproxy:latest
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user sidahmedfaisal/udagram-api-user:latest
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed sidahmedfaisal/udagram-api-feed:latest
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend sidahmedfaisal/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push sidahmedfaisal/udagram-reverseproxy:latest
  - docker push sidahmedfaisal/udagram-api-user:latest
  - docker push sidahmedfaisal/udagram-api-feed:latest
  - docker push sidahmedfaisal/udagram-frontend:latest