- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-api-frontend ./udagram-api-frontend
- docker build -t udagram-reverseproxy ./udagram-reverseproxy

# Tagging
- docker tag udagram-api-feed sudkul/udagram-api-feed:v1
- docker tag udagram-api-user sudkul/udagram-api-user:v1
- docker tag udagram-api-frontend sudkul/udagram-api-frontend:v1
- docker tag udagram-reverseproxy sudkul/udagram-reverseproxy:v1
# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push sudkul/udagram-api-feed:v1
- docker push sudkul/udagram-api-user:v1
- docker push sudkul/udagram-api-frontend:v1
- docker push sudkul/udagram-reverseproxy:v1